# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-30 23:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='last_update',
        ),
    ]
